### ISSUE TITLE
Feature Request: Option to exclude files and/or directories

### ISSUE THREAD

**Issue by mshiltonj** [philbooth/complexity-report#31]
I'm trying to run cr on a node project.  Dependent files in the node_modules directories are causing fatal errors in escomplex-js.  I don't think the fatal errors are incorrect, but I would like to be able to exclude all node_modules/* files from the complexity report.

More generally, I'd like to be able to exclude arbitrary files and directories from the report.

For example:
    cr -p '*.js' --exclude_directory='./node_modules' 

or similar.

Thanks for the great project!

**Comment by philbooth** [comment]
Fixed by #40, closing.
