### ISSUE TITLE
Fatal error [getReports]: Line 4: Illegal return statement - Mac OS X

### ISSUE THREAD

**Issue by tundo91** [philbooth/complexity-report#35]
Executing:
```
cr  --forin --trycatch --newmi --filepattern '(?:app(?!\/vendor)|test\/*)[\/\w]*\.js' -m 10 .
```
I get only this error:
`Fatal error [getReports]: Line 4: Illegal return statement`

Mac OS X 10.9

**Comment by philbooth** [comment]
Closing due to lack of feedback, but feel free to reopen and comment if there's still an issue.
