### ISSUE TITLE
How can complexity-report integrate with CI, for example Jenkins.

### ISSUE THREAD

**Issue by ysihaoy** [philbooth/complexity-report#36]
On the wiki page, it said "The tool can be configured to fail when complexity metrics pass a specified threshold, to aid its usefulness in automated environments / CI."

Are there some document can tell how can it integrate with Jenkins and put threshold on that? It seems less document about that one web.

**Comment by thalesfsp** [comment]
No :)

**Comment by philbooth** [comment]
This should be fixed by #44. I didn't realise the exit code itself was broken, sorry.
