### ISSUE TITLE
DOS line endings prevent command line execution from working on MacOS

### ISSUE THREAD

**Issue by rmurphey** [philbooth/complexity-report#9]
After installing the tool globally and trying to run it from the command line, I got the following error:

```
env: node\r: No such file or directory
```

Changing the filetype of the executable to unix instead of dos addressed the issue for me. I can open a PR, but don't want to break anything if the DOS filetype is important to you :)

**Comment by philbooth** [comment]
Closing this issue as it seems to have been dead for some time now.
